version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=
      - DB_NAME=ahg_procurement
      - PORT=5000
      - JWT_SECRET=your_jwt_secret_key_here
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=ahg_procurement
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/database/mysql_schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  db_data:
